bookingbnb/bnb/urls.py
from django.conf.urls import url

from . import views

app_name = 'bnb'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^addusr$', views.add_user, name="add_user"),
    url(r'^identification$', views.identification, name="identification"),
    url(r'^user_page$', views.user_page, name="user_page"),
    url(r'^admin_page$', views.admin_page, name="admin_page"),
    url(r'^delete_user$', views.delete_user, name="delete_user"),
    url(r'^promote_user$', views.promote_user, name="promote_user"),
]

bookingbnb/bookingbnb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^bnb/', include('bnb.urls')),
    url(r'^admin/', admin.site.urls),
]

bookingbnb/bnb/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    account = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    mail = models.EmailField()
    isadmin = models.BooleanField(default=False)

    def __str__(self):
        return ("account: " + self.account)

bookingbnb/bnb/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from .models import User


# Create your views here.
def index(request):
    return HttpResponse("Hello, world. You're at the bnb index.")


def login(request):
    return render(request, 'bnb/login.html')


def register(request):
    return render(request, 'bnb/register.html')


def add_user(request):
    print(request.POST)
    previous_url = request.META.get('HTTP_REFERER')
    from_admin_page = False
    add_user_success = False
    if previous_url.split('/')[-1] == "admin_page":
        from_admin_page = True

    if request.POST['password'] != request.POST['confirm_password']:
        messages.error(request,
                       'Password and Confirm Password are inconsistent')
    elif not isvalid_mailformat(request.POST['mail']):
        messages.error(request,
                       'Email format is not valid')
    else:
        account = request.POST['account']
        if User.objects.filter(account=account).exists():
            messages.error(request,
                           'The account has already existed')
        else:
            password = request.POST['password']
            name = request.POST['name']
            mail = request.POST['mail']
            isadmin = False
            if from_admin_page and request.POST['identity']=='admin':
                isadmin = True

            user = User(account=account,
                        password=password,
                        name=name,
                        mail=mail,
                        isadmin=isadmin)
            user.save()
            add_user_success = True

    if from_admin_page:
        return HttpResponseRedirect(reverse('bnb:admin_page'))
    else:
        if add_user_success:
            return HttpResponseRedirect(reverse('bnb:login'))
        else:
            return HttpResponseRedirect(reverse('bnb:register'))

def isvalid_mailformat(mail):
    if '@' not in mail or '.' not in mail:
        return False
    else:
        return True


def identification(request):
    account = request.POST['account']
    request.session['_old_post'] = request.POST
    if User.objects.filter(account=account).exists():
        user = User.objects.get(account=account)
        if user.isadmin:
            return HttpResponseRedirect(reverse('bnb:admin_page'))
        else:
            return HttpResponseRedirect(reverse('bnb:user_page'))
    else:
        messages.error(request,
                       'This user is not registered yet')
        return HttpResponseRedirect(reverse('bnb:login'))


def user_page(request):
    old_post = request.session.get('_old_post')
    account = old_post['account']
    user = User.objects.get(account=account)
    context = {'user': user}
    return render(request, 'bnb/user_page.html', context)


def admin_page(request):
    user_list = User.objects.all()
    old_post = request.session.get('_old_post')
    account = old_post['account']
    theuser = User.objects.get(account=account)
    context = {'theuser': theuser, 'user_list': user_list}
    return render(request, 'bnb/admin_page.html', context)


def delete_user(request):
    uid = request.GET['uid']
    User.objects.filter(pk=int(uid)).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def promote_user(request):
    uid = request.GET['uid']
    user = User.objects.get(pk=int(uid))
    user.isadmin = True
    user.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))    

bookingbnb/bnb/templates/bnb/add_user_form.html
<div class="form-group row justify-content-center">
    <label for="account" class="col-xs-3 col-form-label mr-2 sr-only">Account</label>
    <div class="col-xs-9">
        <input type="text" class="form-control" id="account" name="account" placeholder="Account" required>
    </div>
</div>
<div class="form-group row justify-content-center">
    <label for="password" class="col-xs-3 col-form-label mr-2 sr-only">Password</label>
    <div class="col-xs-9">
        <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
    </div>
</div>
<div class="form-group row justify-content-center">
    <label for="confirm_password" class="col-xs-3 col-form-label mr-2 sr-only">Confirm Password</label>
    <div class="col-xs-9">
        <input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Confirm Password" required>
    </div>
</div>
<div class="form-group row justify-content-center">
    <label for="name" class="col-xs-3 col-form-label mr-2 sr-only">Name</label>
    <div class="col-xs-9">
        <input type="text" class="form-control" id="name" name="name" placeholder="Name" required>
    </div>
</div>
<div class="form-group row justify-content-center">
    <label for="mail" class="col-xs-3 col-form-label mr-2 sr-only">Email</label>
    <div class="col-xs-9">
        <input type="mail" class="form-control" id="mail" name="mail" placeholder="Email" required>
    </div>
</div>

bookingbnb/bnb/templates/bnb/admin_page.html
{% extends 'bnb/base.html' %}
{% block title %}admin page{% endblock %}
{% block content %}
	<style>

		body {
	    padding-top: 1em;
	    }
		.title{
		    background-color: pink;
		    color: white;
		    text-align: center;
		    font-family: "Courier New", Georgia, Serif;
		}

		.table td {
		   text-align: center;   
		}

		.table th {
		   text-align: center;   
		}
	</style>
	<div class="container title">
	    <h1 class="display-3">Admin Page</h1>
	</div>
	<div class="container">
		<div class="row justify-content-end">
			<button style="width: auto" type="submit" class="btn btn-outline-warning" data-toggle="modal" data-target="#add_user_modal">新增使用者</button>
			<form style="display: inline;" action="{% url 'bnb:login' %}">
				<button style="width: auto; margin-left: 5px" type="submit" class="btn btn-outline-warning">登出</button>
			</form>
		</div>
	</div>

	<div class="container">
	    {% if messages %}
	        <script type="text/javascript">
	        {% for message in messages %}
	            alert("{{ message|safe }}")
	        {% endfor %}
	        </script>
	    {% endif %}
	</div>

	<!-- Add User Modal -->
	<div class="modal fade" id="add_user_modal" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
			    <div class="modal-header">
			    	<h4 class="modal-title">Add New User</h4>
			        <button type="button" class="close" data-dismiss="modal">&times;</button>
			    </div>
			    <div class="modal-body">
			    	<form action="{% url 'bnb:add_user' %}" method="post">
			    	{% csrf_token %}
			    	    {% include 'bnb/add_user_form.html' %}
			    	    <div class="form-group row justify-content-center">
			    	    	<label class="custom-control custom-radio">
			    	    		<input id="normal" name="identity" type="radio" value="normal" class="custom-control-input" required>
			    	    		<span class="custom-control-indicator"></span>
			    	    		<span class="custom-control-description">Normal User</span>
			    	    	</label>
			    	    	<label class="custom-control custom-radio">
			    	    		<input id="admin" name="identity" type="radio" value="admin" class="custom-control-input">
			    	    		<span class="custom-control-indicator"></span>
			    	    		<span class="custom-control-description">Admin</span>
			    	    	</label>
			    	    </div>
			    	    
			    	    <div class="form-group row justify-content-center">
			    	        <div class="col-xs-9">
			    	            <button style="width: auto" type="submit" class="btn btn-outline-info">註冊</button>
			    	        </div>            
			    	    </div>
			    	</form>
			    </div>
			    <div class="modal-footer">
			    </div>

			</div>
		</div>
	</div>

	<!-- User List Table-->
	{% if user_list %}
    <div class="container">
	    <table class="table">
	    <thead>
	    	<tr>
	    		<th>姓名</th>
	    		<th>帳號</th>
	    		<th>郵件</th>
	    		<th>身份</th>
	    	</tr>
	    </thead>
	    <tbody>
	    	{% if theuser %}
	    	<tr class="table-info">
		        <td class="name">{{ theuser.name }}</td>
		        <td class="account">{{ theuser.account }}</td>
		        <td class="mail">{{ theuser.mail }}</td>
		        <td class="isadmin">admin</td>
		        <td>
		        </td>
	        </tr>
	        {% endif %}
	        {% for u in user_list %}
	        {% if u.id != theuser.id %}
		    <tr>
		        <td class="name">{{ u.name }}</td>
		        <td>{{ u.account }}</td>
		        <td>{{ u.mail }}</td>
		        <td>
		        	{% if u.isadmin %}
		        	admin
		        	{% else%}
		        	nomal
		        	{% endif%}
		        </td>
		        <td>
		        	<form action="{% url 'bnb:promote_user' %}" style="display: inline;">
		        		<button style="width: auto" type="submit" class="btn btn-outline-info" name="uid" value="{{u.id}}">Promote</button>
		        	</form>
		        	<form action="{% url 'bnb:delete_user' %}" style="display: inline;">
		        		<button style="width: auto" type="submit" class="btn btn-outline-info" name="uid" value="{{u.id}}">刪除</button>
		        	</form>
		        </td>
	        </tr>
	        {% endif %}
	        {% endfor %}
        </tbody>
        </table>
    </div>
    {% else %}
    <p>No users are available.</p>
    {% endif %}

{% endblock %}

bookingbnb/bnb/templates/bnb/base.html
<!doctype html>
<html>
    <head>
    	<title>{% block title %}{% endblock %}</title>
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    	<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    </head>
    <body>
    	{% block content%}{% endblock %}
    </body>
</html>

bookingbnb/bnb/templates/bnb/login.html
{% extends 'bnb/base.html' %}
{% block title %}login{% endblock %}
{% block content %}
    <style>
    body {
    padding-top: 1em;
    }   
    .title{
        background-color: pink;
        color: white;
        text-align: center;
        font-family: "Courier New", Georgia, Serif;
    }
    </style> 
    <div class="container title">
        <h1 class="display-3">Welcome to BookingBnb</h1>
    </div>

    <div class="container">
        {% if messages %}
            <script type="text/javascript">
            {% for message in messages %}
                alert("{{ message|safe }}")
            {% endfor %}
            </script>
        {% endif %}    
    </div>

    <div class="container">
    <form action="{% url 'bnb:identification' %}" method="POST">
    {% csrf_token %}
        <div class="form-group row justify-content-center">
            <label for="account" class="col-xs-3 col-form-label mr-2 sr-only">Account</label>
            <div class="col-xs-9">
                <input type="text" class="form-control" id="account" name="account" placeholder="Account">
            </div>
        </div>
        <div class="form-group row justify-content-center">
            <label for="password" class="col-xs-3 col-form-label mr-2 sr-only">Password</label>
            <div class="col-xs-9">
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
        </div>
        <div class="form-group row justify-content-center">
            <div class="col-xs-9">
                <button style="width: auto" type="submit" class="btn btn-outline-info">登入</button>
            </div>            
        </div>

    </form>
    <hr>
    </div>

    <div class="container">
      <div class="row justify-content-center">
        <div class="col-2">
          還沒有帳號？<a href="{% url 'bnb:register'%}">註冊</a>
        </div>
      </div>
    </div>

{% endblock %}

bookingbnb/bnb/templates/bnb/register.html
{% extends 'bnb/base.html' %}
{% block title %}register{% endblock %}
{% block content %}
    <style>
    body {
    padding-top: 1em;
    }   
    .title{
        background-color: pink;
        color: white;
        text-align: center;
        font-family: "Courier New", Georgia, Serif;
    }
    </style> 
    <div class="container title">
        <h1 class="display-3">Welcome to BookingBnb</h1>
    </div>

    <div class="container">
        {% if messages %}
            <script type="text/javascript">
            {% for message in messages %}
                alert("{{ message|safe }}")
            {% endfor %}
            </script>
        {% endif %}
    </div>

    <div class="container">
    <form action="{% url 'bnb:add_user' %}" method="post">
    {% csrf_token %}
        {% include 'bnb/add_user_form.html' %}
        <div class="form-group row justify-content-center">
            <div class="col-xs-9">
                <button style="width: auto" type="submit" class="btn btn-outline-info">註冊</button>
            </div>            
        </div>
    </form>

    <hr>
    </div>

    <div class="container">
      <div class="row justify-content-center">
        <div class="col-2">
          已經有帳號了？<a href="{% url 'bnb:login' %}">登入</a>
        </div>
      </div>
    </div>

{% endblock %}

bookingbnb/bnb/templates/bnb/user_page.html
{% extends 'bnb/base.html' %}
{% block title %}user page{% endblock %}
{% block content %}
	<style>

		body {
	    padding-top: 1em;
	    }
		.title{
		    background-color: pink;
		    color: white;
		    text-align: center;
		    font-family: "Courier New", Georgia, Serif;
		}

		.table td {
		   text-align: center;   
		}

		.table th {
		   text-align: right;   
		}
	</style>
	<div class="container title">
	    <h1 class="display-3">User Page</h1>
	</div>
    {% if user %}
    	<div class="container">
	        <table class="table">
	        <tbody>
		        <tr>
			        <th>姓名</th>
			        <td>{{ user.name }}</td>
		        </tr>
		        <tr>
			        <th>帳號</th>
			        <td>{{ user.account }}</td>
		        </tr>
		        <tr>
			        <th>郵件</th>
			        <td>{{ user.mail }}</td>
		        </tr>
	        </tbody>
	        </table>
    	</div>
    {% else %}
        <p>No users are available.</p>
    {% endif %}
    <div class="container">
    	<div class="row justify-content-center">
    	<hr>
    	<a href="{% url 'bnb:login'%}">登出</a>
    	</div>
    </div>
{% endblock %}